- name: creating a catalogue component
  become: yes
  hosts: catalogue

  tasks:
  - name: Diasable default nodejs 
    ansible.builtin.command: dnf module disable nodejs -y   # There is no module for disable modules so we are using command modules (ansible.builtin.command)

  - name: enable nodejs 20 versoin
    ansible.builtin.command: dnf module enable nodejs:20 -y 
  - name: Installing Nodejs 
    ansible.builtin.dnf:                                    # Installing a package using {ansible.builtin.dnf} modules
      name: nodejs    
      state: present

  - name: creating system user 
    ansible.builtin.user:                                  # creating a user using  {ansible.builtin.user} modules
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create app directoty
    ansible.builtin.file:                                 # creating a directory using ( ansible.builtin.file) modules
      path: /app
      state: directory

  - name: Download catalogue application code 
    ansible.builtin.get_url:                                 # dowloading the files using ( ansible.builtin.get_url) module
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip
    
  - name: Extract the catalogue code 
    ansible.builtin.unarchive:                           # Unzip or extracting the files using ( ansible.builtin.unarchive) module
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies
    community.general.npm:                               # Installing npm package using  ( community.general.npm ) modules
      path: /app

  - name: copy catalogue service to system directoy 
    ansible.builtin.copy:                               # copy the modules from source to destination using ( ansible.builtin.copy) module
      src: catalogue.service
      dest: /etc/systemd/system/

  - name: Systemctl daemon reload
    ansible.builtin.systemd_service:                    # systemctl restarting daemon using ( ansible.builtin.systemd_service) module
      daemon_reload: yes

  - name: start and enable catalogue services
    ansible.builtin.service:                            # to restarting and enable service ( ansible.builtin.service) module
      name: catalogue
      state: restarted
      enabled: yes

  - name: copying mongodb repos
    ansible.builtin.copy:                             # copying the files from source to destination in ansible using ( ansible.builtin.copy) module
      src: mongo.repo 
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: Install mongodb clinet 
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: check the products loaded or not
    ansible.builtin.command: mongosh --host mongodb.vinodh.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print the catalogue output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.command: mongosh --host mongodb.vinodh.site </app/db/master-data.js
    when: catalogue_output.stdout < 0
    










    

