- name: configuring the frontend component
  become: yes
  hosts: forntend
  tasks:
  - name: disabling default nginx 
    ansible.builtin.command: dnf module disable nginx -y
   
  - name: enabling default nginx-1:24 verssion
    ansible.builtin.command: dnf module enable nginx:1.24 -y
  
  - name: install nginx 
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: Start and Enable Nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove the html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Download frontend code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: Extract the frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip 
      dest: /usr/share/nginx/html
      remote_src: true

  - name: remove default nginx configuration
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

  - name: copy nginx.conf 
    ansible.builtin.copy:
     src: nginx.conf
     dest: /etc/nginx/nginx.conf
     remote_src: yes

  - name: Restart Nginx service
    ansible.builtin.service:
      name: nginx
      state: restarted






