- name: configuring mongodb server
  become: yes
  hosts: mongodb
  tasks:
  - name: copying mongodb repos
    ansible.builtin.copy:      # copy the modules from source to destination
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Installing mongodb server
    ansible.builtin.dnf:      # Install the packages on redhat linux server ( we can use package module also)
      name:  mongodb-org
      state: present 

  - name: start and enable mongodb 
    ansible.builtin.service:  # Enable and starting any services in Ansible using ansible.builtin.service module
      name: mongod
      state: started
      enabled: yes
  - name: allow remote connections
    ansible.builtin.replace:   # Replacing the values using ansible.builtin.replace 
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: restarted mongodb 
    ansible.builtin.service:  # for starting the services using ansible.builtin.service
      name: mongod
      state: restarted
      


